name: Bluesky to Twitter Bot

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BLUESKY_HANDLE_ENV: ${{ secrets.BLUESKY_HANDLE_ENV }}
          BLUESKY_PASSWORD_ENV: ${{ secrets.BLUESKY_PASSWORD_ENV }}
          TARGET_ACCOUNT_ENV: ${{ secrets.TARGET_ACCOUNT_ENV }}
          TW_CONSUMER_KEY_ENV: ${{ secrets.TW_CONSUMER_KEY_ENV }}
          TW_CONSUMER_SECRET_ENV: ${{ secrets.TW_CONSUMER_SECRET_ENV }}
          TW_ACCESS_TOKEN_ENV: ${{ secrets.TW_ACCESS_TOKEN_ENV }}
          TW_ACCESS_SECRET_ENV: ${{ secrets.TW_ACCESS_SECRET_ENV }}
        run: python bot.py
